import { useState } from "react";
import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { getArchitecture, listRepos, searchCode, traceCode, type CodeFunction } from "../../api/code";
import { Badge } from "../../components/Badge";
import { type Column, DataTable } from "../../components/DataTable";
import { ErrorNotice } from "../../components/ErrorNotice";
import { JsonViewer } from "../../components/JsonViewer";
import styles from "../../components/ui.module.css";

function functionColumns(onTrace: (fn: CodeFunction) => void): Column<CodeFunction>[] {
  return [
    { key: "name", header: "Function", render: (fn) => <code>{fn.name}</code> },
    { key: "repo", header: "Repo", render: (fn) => fn.repo },
    { key: "path", header: "Path", render: (fn) => fn.path },
    { key: "summary", header: "Summary", render: (fn) => fn.summary },
    {
      key: "trace",
      header: "",
      render: (fn) => (
        <button type="button" onClick={() => onTrace(fn)}>
          Trace
        </button>
      ),
    },
  ];
}

export function Code() {
  const { team = "" } = useParams<{ team: string }>();
  const [q, setQ] = useState("");
  const [appliedQ, setAppliedQ] = useState("");
  const [trace, setTrace] = useState<{ fn: CodeFunction; direction: "outbound" | "inbound" } | null>(null);

  const repos = useQuery({ queryKey: ["admin", "teams", team, "code", "repos"], queryFn: () => listRepos(team) });
  const search = useQuery({
    queryKey: ["admin", "teams", team, "code", "search", appliedQ],
    queryFn: () => searchCode(team, { q: appliedQ || undefined, limit: 25 }),
    enabled: appliedQ.length > 0,
  });
  const architecture = useQuery({
    queryKey: ["admin", "teams", team, "code", "architecture"],
    queryFn: () => getArchitecture(team),
  });
  const traceQuery = useQuery({
    queryKey: ["admin", "teams", team, "code", "trace", trace?.fn.id, trace?.direction],
    queryFn: () => traceCode(team, trace!.fn.id, { direction: trace!.direction }),
    enabled: trace !== null,
  });

  return (
    <div>
      <p>
        Read-only: the code graph is derived from git and regenerated by the extractor. There is no edit affordance
        here.
      </p>

      <div className={styles.section}>
        <h3>Indexed repos</h3>
        {repos.error && <ErrorNotice error={repos.error} />}
        {repos.data && repos.data.length > 0 ? (
          repos.data.map((repo) => (
            <Badge key={repo} tone="neutral">
              {repo}
            </Badge>
          ))
        ) : (
          <p>No repos indexed yet.</p>
        )}
      </div>

      <div className={styles.section}>
        <h3>Search</h3>
        <form
          className={styles.filterBar}
          onSubmit={(e) => {
            e.preventDefault();
            setAppliedQ(q);
          }}
        >
          <div className={styles.filterField}>
            <label htmlFor="code-q">Query</label>
            <input id="code-q" value={q} onChange={(e) => setQ(e.target.value)} />
          </div>
          <button type="submit">Search</button>
        </form>
        {search.error && <ErrorNotice error={search.error} />}
        {search.data && (
          <DataTable
            columns={functionColumns((fn) => setTrace({ fn, direction: "outbound" }))}
            rows={search.data}
            getRowKey={(fn) => fn.id}
            emptyMessage="No matching functions."
          />
        )}
      </div>

      {trace && (
        <div className={styles.section}>
          <h3>
            {trace.direction === "outbound" ? "Calls from" : "Callers of"} <code>{trace.fn.name}</code>
          </h3>
          <div className={styles.filterBar}>
            <button type="button" onClick={() => setTrace({ ...trace, direction: "outbound" })}>
              Outbound
            </button>
            <button type="button" onClick={() => setTrace({ ...trace, direction: "inbound" })}>
              Inbound
            </button>
            <button type="button" onClick={() => setTrace(null)}>
              Close
            </button>
          </div>
          {traceQuery.error && <ErrorNotice error={traceQuery.error} />}
          {traceQuery.data && (
            <DataTable
              columns={functionColumns((fn) => setTrace({ fn, direction: trace.direction }))}
              rows={traceQuery.data}
              getRowKey={(fn) => fn.id}
              emptyMessage="No related functions."
            />
          )}
        </div>
      )}

      <div className={styles.section}>
        <h3>Architecture</h3>
        {architecture.error && <ErrorNotice error={architecture.error} />}
        {architecture.data && architecture.data.communities.length > 0 ? (
          architecture.data.communities.map((community, i) => (
            <JsonViewer key={i} value={community} label={`community ${i + 1}`} />
          ))
        ) : (
          <p>No architecture summary available.</p>
        )}
      </div>
    </div>
  );
}
